### PR TITLE
fix GetChars in linux/macOS

### LINKED ISSUE #2206: [BUG] FString related compilation error in src/posix/i_steam.cpp
### GZDoom version

commit 6055ff029d5e87e84aaaf698bb430656e1e16588

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Debian GNU/Linux 12 (bookworm) x86_64

### Relevant hardware info

Intel i7-6700 / Intel HD Graphics 530

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After latest `FString` related refactoring, compilation fails with:
```
/home/alex/prj/games/gzdoom/src/posix/i_steam.cpp: In function ‘TArray<FString> I_GetSteamPath()’:
/home/alex/prj/games/gzdoom/src/posix/i_steam.cpp:205:66: error: cannot convert ‘FString’ to ‘const char*’
  205 |                         SteamInstallFolders = ParseSteamRegistry(regPath);
      |                                                                  ^~~~~~~
      |                                                                  |
      |                                                                  FString
/home/alex/prj/games/gzdoom/src/posix/i_steam.cpp:119:55: note:   initializing argument 1 of ‘TArray<FString> ParseSteamRegistry(const char*)’
  119 | static TArray<FString> ParseSteamRegistry(const char* path)
      |                                           ~~~~~~~~~~~~^~~~
/home/alex/prj/games/gzdoom/src/posix/i_steam.cpp:224:38: error: cannot convert ‘FString’ to ‘const char*’
  224 |                         if(DirExists(candidate))
      |                                      ^~~~~~~~~
      |                                      |
      |                                      FString
In file included from /home/alex/prj/games/gzdoom/src/./doomtype.h:31,
                 from /home/alex/prj/games/gzdoom/src/./d_main.h:31,
                 from /home/alex/prj/games/gzdoom/src/posix/i_steam.cpp:42:
/home/alex/prj/games/gzdoom/src/common/utility/cmdlib.h:42:28: note:   initializing argument 1 of ‘bool DirExists(const char*)’
   42 | bool DirExists(const char *filename);
      |                ~~~~~~~~~~~~^~~~~~~~
make[2]: *** [src/CMakeFiles/zdoom.dir/build.make:112: src/CMakeFiles/zdoom.dir/posix/i_steam.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:739: src/CMakeFiles/zdoom.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. `cmake .. -DNO_FMOD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/prj/games/ZMusic/build_install && make`
2. See above.

### Your configuration

_No response_

### Provide a Log

_No response_

### PR DESCRIPTION
**Pull request by RicardoLuis0**
fixes #2206

### CODE REVIEW

File: src/gameconfigfile.cpp [hunk 1]
```diff
@@ -156,14 +156,14 @@ FGameConfigFile::FGameConfigFile ()
 	{
 		SetSection("SoundfontSearch.Directories", true);
```
Comment (ZoomPicard) [inline src/gameconfigfile.cpp:157]: Not entirely sure but I think a change here meant that the included gzdoom.sf2 soundfont will no longer load from the build/soundfonts library and only paths specified in the ini file were valid. I lost midi sound until I copied the gzdoom.sf2  to ~/.config/gzdoom/soundfonts lib which was a valid path in the ini file. This on a linux system. Was that intentional?

Comment (RicardoLuis0) [reply src/gameconfigfile.cpp:157]: well, that line wasn't changed, all i added in that file was GetChars to the places where it wasn't compiling
