### PR TITLE
Fix build under Solaris

### LINKED ISSUE #3040: [BUG] -Fpie is added despite not being valid in Solaris either
### GZDoom version

master a02892389d55211757b18bd269d093ad203403b7

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Other

### Please describe your specific OS version

OpenIndiana 2025.04

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Trying to build fails on the added option -pie, which is only supported on Linux

The current check only excludes Haiku and mingw.

Note: a [support module](https://cmake.org/cmake/help/latest/module/CheckPIESupported.html) is available on CMAKE to add -Fpie when supported (however seems not to work, since it reports OpenIndiana/Illumos as supporting pie)

https://cmake.org/cmake/help/latest/module/CheckPIESupported.html

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Build on a Solaris Platform
2. `cmake .. -DNO_FMOD=ON -DCMAKE_BUILD_TYPE=release` 
3.

### Your configuration

```ini
cmake .. -DNO_FMOD=ON -DCMAKE_BUILD_TYPE=release

Patched CMakeLists.txt to add a stdint check (another issue is coming)
```

### Provide a Log

```
c++: error: -pie is not supported in this configuration
gmake[2]: *** [tools/re2c/CMakeFiles/re2c.dir/build.make:948: tools/re2c/re2c] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:658: tools/re2c/CMakeFiles/re2c.dir/all] Error 2
```

### LINKED ISSUE #3041: [BUG] Missing stdint.h check for Unix platforms
### GZDoom version

_No response_

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Other

### Please describe your specific OS version

OpenIndiana 2025.04

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Building on Illumos fails with a override of stdint

This occurs because the HAVE_STDINT_H is not set in cmake and Solaris/Illumnos has a stdint.h which clash

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Try to build on a Illumnos platform
2. cmake .. -DNO_FMOD=ON -DCMAKE_BUILD_TYPE=release
3.

### Your configuration

```ini
cmake .. -DNO_FMOD=ON -DCMAKE_BUILD_TYPE=release
```

### Provide a Log

```
In file included from /export/home/signed/build/gzdoom/tools/re2c/src/codegen/bitmap.h:4,
                 from /export/home/signed/build/gzdoom/tools/re2c/src/codegen/bitmap.cc:4:
/export/home/signed/build/gzdoom/tools/re2c/src/util/c99_stdint.h:138:18: error: conflicting declaration 'typedef int16_t int_fast16_t'
  138 | typedef int16_t  int_fast16_t;
      |                  ^~~~~~~~~~~~
In file included from /usr/include/sys/types.h:55,
                 from /usr/include/sys/wait.h:37,
                 from /usr/include/stdlib.h:46,
                 from /usr/gcc/14/include/c++/14.2.0/cstdlib:79,
                 from /usr/gcc/14/include/c++/14.2.0/bits/stl_algo.h:71,
                 from /usr/gcc/14/include/c++/14.2.0/algorithm:61,
                 from /export/home/signed/build/gzdoom/tools/re2c/src/codegen/bitmap.cc:1:
/usr/include/sys/int_types.h:136:33: note: previous declaration as 'typedef int int_fast16_t'
  136 | typedef int                     int_fast16_t;
      |                                 ^~~~~~~~~~~~
/export/home/signed/build/gzdoom/tools/re2c/src/util/c99_stdint.h:142:18: error: conflicting declaration 'typedef uint16_t uint_fast16_t'
  142 | typedef uint16_t uint_fast16_t;
      |                  ^~~~~~~~~~~~~
/usr/include/sys/int_types.h:147:33: note: previous declaration as 'typedef unsigned int uint_fast16_t'
  147 | typedef unsigned int            uint_fast16_t;
      |                                 ^~~~~~~~~~~~~
/export/home/signed/build/gzdoom/tools/re2c/src/util/c99_stdint.h:151:25: error: conflicting declaration 'typedef int intptr_t'
  151 |    typedef          int intptr_t;
      |                         ^~~~~~~~
/usr/include/sys/int_types.h:120:33: note: previous declaration as 'typedef long int intptr_t'
  120 | typedef long                    intptr_t;
      |                                 ^~~~~~~~
/export/home/signed/build/gzdoom/tools/re2c/src/util/c99_stdint.h:152:25: error: conflicting declaration 'typedef unsigned int uintptr_t'
  152 |    typedef unsigned int uintptr_t;
      |                         ^~~~~~~~~
/usr/include/sys/int_types.h:121:33: note: previous declaration as 'typedef long unsigned int uintptr_t'
  121 | typedef unsigned long           uintptr_t;
      |                                 ^~~~~~~~~
```

### PR DESCRIPTION
**Pull request by the-phinet**
A number of changes to enable a successful build using OpenIndiana 20250606

Fixes #3041
Fixes #3040

### CODE REVIEW

File: src/common/engine/serializer.cpp [hunk 1]
```diff
@@ -1060,6 +1061,7 @@ FSerializer& Serialize(FSerializer& arc, const char* key, char& value, char* def
 	value = (int8_t)vv;
 	return arc;
 }
+#endif
```
Comment (madame-rachelle) [inline src/common/engine/serializer.cpp:1064]: This function is critical, we can't just block it out arbitrarily on platforms. Do you have some sort of replacement available?

**Review by madame-rachelle — CHANGES_REQUESTED** [review]

File: src/common/engine/serializer.cpp (hunk 1 above)
Comment (the-phinet) [reply src/common/engine/serializer.cpp:1064]: Hmmm, so the issue is that Solaris treats char and int8_t as identical, and the compiler is rather strict about it, so the build fails.

```
[ 39%] Building CXX object src/CMakeFiles/zdoom.dir/common/engine/serializer.cpp.o
/export/home/marcus/gzdoom/src/common/engine/serializer.cpp:1066:14: error: redefinition of 'FSerializer& Serialize(FSerializer&, const char*, int8_t&, int8_t*)'
 1066 | FSerializer &Serialize(FSerializer &arc, const char *key, int8_t &value, int8_t *defval)
      |              ^~~~~~~~~
/export/home/marcus/gzdoom/src/common/engine/serializer.cpp:1056:14: note: 'FSerializer& Serialize(FSerializer&, const char*, char&, char*)' previously defined here
 1056 | FSerializer& Serialize(FSerializer& arc, const char* key, char& value, char* defval)
      |              ^~~~~~~~~
*** Error code 1
```

Looking at the implementations of the conflicting functions, they seem identical to me. Honestly, I might be missing something, though.

If I'm correct, would a check that looks to see if the types conflict be better than a check for solaris? This is the best I can figure out: `#if defined(__CHAR_UNSIGNED__) || (CHAR_BIT != 8) || (INT8_MAX != SCHAR_MAX)`. But this is definitely incorrect, as the check is gives the same result as Linux, so as expected the Linux build now fails.

With the masked out function on Solaris's end, both a Linux build and a Solaris build can happily connect

Screenshot_20250617_112727

Comment (RicardoLuis0) [reply src/common/engine/serializer.cpp:1064]: > This function is critical, we can't just block it out arbitrarily on platforms. Do you have some sort of replacement available?

seems fine to me, this serializes single chars as ints not strings, and if it was needed in solaris it would simply fail at the linking stage

**Comment by madame-rachelle** [comment]
Alright, I am taking you at your word here, as I don't want to set up a Solaris environment to test this. Serialize is also used for save games though - so that should be tested, also, making sure you can use the same save from Solaris on both non-Solaris and Solaris.

**Comment by RicardoLuis0** [comment]
> Alright, I am taking you at your word here, as I don't want to set up a Solaris environment to test this. Serialize is also used for save games though - so that should be tested, also, making sure you can use the same save from Solaris on both non-Solaris and Solaris.

yeah, but this is the kind of thing that if it'd fail, it'd fail during building/linking, not during execution, so if it compiles/runs at all it's fine

**Comment by the-phinet** [comment]
Saving works fine.

My poor laptop did not enjoy recording this

[Screencast_20250618_162646.webm](https://github.com/user-attachments/assets/9b95c724-26f9-4602-bf38-e7b2e71c4596)

**Comment by coelckers** [comment]
This really should use C++ compile time checks (std::is_same) for disabling duplicated overloads instead of #ifdef. It's only a question of time until this causes problems somewhere else.
The entire savegame system should probably be rewritten using C++ concepts to be less vulnerable to outlier implementations of stdint.h types.

Using a  generic char for int8_t is stupid,, though. What does Solaris do if char is made unsigned (like the Build engine requires?)
